apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: keycloak
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - env:
            - name: DB_VENDOR
              value: h2
            - name: KEYCLOAK_IMPORT
              value: /opt/keycloak/realm.json
            - name: KEYCLOAK_PASSWORD
              value: password
            - name: KEYCLOAK_USER
              value: admin
          image: jboss/keycloak:latest
          name: keycloak
          ports:
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - mountPath: /opt/keycloak/realm.json
              name: keycloak_pvc
      restartPolicy: Always
      volumes:
        - name: keycloak_pvc
          persistentVolumeClaim:
            claimName: keycloak_pvc
      readinessProbe:
        httpGet:
          path: /realms/master
          port: 8080

#this runs in port 32534