apiVersion: apps/v1
kind: Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: keycloak
  strategy:
    type: Recreate
  template:
    spec:
      containers:
        - env:
            - name: DB_VENDOR
              value: h2
            - name: KEYCLOAK_IMPORT
              value: /opt/keycloak/realm.json
            - name: KEYCLOAK_PASSWORD
              value: password
            - name: KEYCLOAK_USER
              value: admin
          image: jboss/keycloak:latest
          name: keycloak
          ports:
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - mountPath: /opt/keycloak/realm.json
              name: keycloak-pvc
      restartPolicy: Always
      volumes:
        - name: keycloak-pvc
          persistentVolumeClaim:
            claimName: keycloak-pvc
status: {}
---
apiVersion: v1
kind: Service
name: keycloak
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
status:
  loadBalancer: {}