apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring
spec:
  rules:
  - host: devops22.cloudns.ph
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: spring-boot-app
            port:
              number: 80