version: '3'
services:
  mysql:
    image: mysql:latest
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: devops_2022
      MYSQL_USER: springuser
      MYSQL_PASSWORD: thePassword
  
  mailhog:
      image: mailhog/mailhog
      container_name: 'mailhog'
      ports:
        - "1025:1025"
        - "8025:8025"

  keycloak:
    depends_on:
      - mysql
    container_name: keycloak
    environment:
      DB_VENDOR: mysql
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
    image: jboss/keycloak:latest
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - local-keycloak

networks:
  local-keycloak: