version: '3'
services:
  mysql:
    image: mysql:latest
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: devops_2022
      MYSQL_USER: springuser
      MYSQL_PASSWORD: thePassword
  
  mailhog:
      image: mailhog/mailhog
      container_name: 'mailhog'
      ports:
        - "1025:1025"
        - "8025:8025"

  keycloak:
    container_name: keycloak
    environment:
      DB_VENDOR: h2
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      KEYCLOAK_IMPORT: /opt/keycloak/realm.json
    image: jboss/keycloak:latest
    volumes:
            - '/home/vagrant/realm.json:/opt/keycloak/realm.json'
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - local-keycloak

  spring-boot-app:
    depends_on:
      - mysql
      - keycloak
      - mailhog
    container_name: spring_boot_app
    image: spring_boot_app
    ports:
    - "80:80"

networks:
  local-keycloak: