---
- hosts: testbed
  become: true

  vars_prompt:
  - name: fqdn
    prompt: Please enter the fqdn that your app will be hosted in (leave blank for local ip)
    private: no
    
  tasks:

  - name: install default jdk
    apt:
      name: default-jdk
      state: present

  - name: download Keycloack tar
    shell: sudo wget https://github.com/keycloak/keycloak/releases/download/18.0.0/keycloak-18.0.0.tar.gz -P /opt -N

  - name: extract the package
    shell: sudo tar -xvzf /opt/keycloak-18.0.0.tar.gz -C /opt

  - name: get public IP
    ipify_facts:
    register: public_ip

  - name: create realm json file
    ansible.builtin.template:
        src: keycloak_realm.j2
        dest: /opt/keycloak-18.0.0/realm.json
        owner: vagrant
        group: vagrant
        mode: '0644'

  - name: import realm
    shell: cd  /opt/keycloak-18.0.0/bin/ && ./kc.sh import --file /opt/keycloak-18.0.0/realm.json


  - name: run
    #shell: cd /opt/keycloak-18.0.0/bin/
    shell: cd /opt/keycloak-18.0.0/bin/ && screen -d -m ./kc.sh start-dev >> log.txt
