---
- hosts: testbed
  become: true

  vars_prompt:
  - name: user
    prompt: Please enter the user
    private: false

  tasks:
  - name: install microk8s  
    shell: snap install microk8s --classic

  - name: permissions 
    shell: sudo usermod -a -G microk8s {{ user }}

  - name: permissions2
    file: dest=~/.kube owner={{ user }} mode=u=rwX,g=rX,o=rX recurse=yes

  - name: reload permissions
    shell: newgrp microk8s
  # TODO: this was hanging up when I ran it

  - name: enable helm for Mailhog
    shell: microk8s enable helm3

  - name: yml files copy
    copy:
      src: kubernetes/
      dest: /home/{{ user }}/kubernetes/
      mode: 0644

  - name: apply keycloak.yml
    shell: microk8s kubectl apply -f /home/{{ user }}/kubernetes/keycloack.yml
    

  - name: create the mysql persistent volume directory
    shell: cd /home/{{user}}/ | mkdir mysql-kube  


  - name: apply the pv
    shell: microk8s kubectl apply -f /home/{{user}}/kubernetes/mysql-pv.yml

  - name: claim the pv
    shell: microk8s kubectl apply -f /home/{{user}}/kubernetes/mysql-pvc.yml
    
  - name: create the Deployment
    shell: microk8s kubectl apply -f /home/{{user}}/kubernetes/mysql.yml
    
  - name: create the Service
    shell: microk8s kubectl apply -f /home/{{user}}/kubernetes/mysql-service.yml  

  - name: mailhog
    shell: cd /home/{{user}}/ | microk8s helm3 repo add codecentric https://codecentric.github.io/helm-charts && microk8s helm3 install mailhog codecentric/mailhog 
    tags: 
      - t