- name: Install and launch MailHog
  hosts: vm
  become: true
  tasks:
  - name : Install Screen
    apt:
      name: screen
      state: present
  - name : Install GoLang
    apt:
      name: golang-go
      state : present
  - name : Install git
    apt :
      name : git
      state : present
  - name : Make Go Path Folder
    file:
      path: ~/go
      state: directory
      mode : '0755'
  - name : Set GOPATH
    set_fact:
      go_path: "{{ lookup('env', 'GOPATH') | default(ansible_env.HOME+'/go', true) }}"
      when: not result|failed
  - name : Clone MailHog
    ansible.builtin.command: go install github.com/mailhog/MailHog@latest
    environment:
      GOPATH: "{{ go_path }}"
  - name : Copy MailHog to bin directory
    ansible.builtin.command: sudo cp ~/go/bin/MailHog /usr/local/bin/Mailhog
  - name: Start MailHog
    shell: screen -d -m Mailhog


