---
- hosts: testbed
  become: true
  become_user: root
  vars:   
    mysql_root_password: password   

  tasks:   
    - name: install mysql-server     
      apt: name=mysql-server update_cache=yes cache_valid_time=3600 state=present

    - name: start up the mysql service  
      shell: "service mysql start"  
    - name: ensure mysql is enabled to run on startup  
      service: name=mysql state=started enabled=true  