---
- hosts: testbed
  become: true

  vars:   
    mysql_root_password: password   

  tasks:   

    - name: run apt-get update
      command: apt-get update

    - name: install mysql-server     
      apt: name=mysql-server update_cache=yes cache_valid_time=3600 state=present

    - name: start up the mysql service  
      shell: "service mysql start"  
    - name: ensure mysql is enabled to run on startup  
      service: name=mysql state=started enabled=true  

    - name: create new sql user
      shell: sudo mysql -e "CREATE USER 'springuser'@'localhost' IDENTIFIED BY 'thePassword';"

    - name: create sql database
      shell: sudo mysql -e "CREATE DATABASE devops_2022;"

<<<<<<< HEAD
    - name: grant all rights to new account on new database
      shell: sudo mysql -e "GRANT ALL PRIVILEGES ON devops_2022.* TO 'springuser'@'localhost';"
=======
    - name: grant all privleges on new user on new database
      shell: sudo mysql -e "GRANT ALL PRIVILEGES ON devops_22.* TO 'springuser'@'localhost';"
>>>>>>> fba3ff4ac63150682a2c2a54552486ee3260c3d7
