---

- name: Clone, build and run spring boot app
  hosts: testbed
  vars_prompt:
  - name: fqdn
    prompt: Please enter the fqdn that your app will be hosted in (leave blank for local ip)
    private: no
  tasks:
    - name: Install git and JDK
      become: true
      apt: 
        name: 
        - default-jdk
        - git
        state: present
    - name: Clone git repository
      shell: |
        git clone https://github.com/thanbimp/Recommendation-Letter-Service
        cd Recommendation-Letter-Service/
        git checkout keycloak
        chmod +x mvnw
    - name: get public IP
      ipify_facts:
      register: public_ip
    - name: create application.properties file
      ansible.builtin.template:
        src: spring_boot.j2
        dest: ~/Recommendation-Letter-Service/application.properties
        owner: vagrant
        group: vagrant
        mode: '0644'
    - name : Build jar
      shell : |
        cd Recommendation-Letter-Service/
        ./mvnw package

    - name : launch jar
      become: true
      shell : |
        cd Recommendation-Letter-Service/
        java -jar target/ds_group_13-0.0.1-SNAPSHOT.jar
